#pragma once

#define VIAL_KEYBOARD_UID {0x0E, 0x2B, 0xCD, 0x9D, 0x2C, 0x60, 0xDC, 0xC5}

#define DYNAMIC_KEYMAP_LAYER_COUNT 16

#define VIAL_TAP_DANCE_ENTRIES 24

#define VIAL_COMBO_ENTRIES 64

#define DYNAMIC_KEYMAP_MACRO_COUNT 32

#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 4 }