# Building options

LTO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
QMK_SETTINGS = no
TAP_DANCE_ENABLE = yes
NKRO_ENABLE = yes
