// Copyright 2023 Danny Nguyen (danny@keeb.io)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

//#define SPLIT_HAND_PIN GP4
//#define USB_VBUS_PIN GP14

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP27
#define SERIAL_USART_RX_PIN GP28
#define SERIAL_USART_PIN_SWAP

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U