#include QMK_KEYBOARD_H

enum layers{
  _BASE,
  _NUM_SYM,
  _NAV
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_BASE] = LAYOUT(
    KC_Q,   KC_W,   KC_E,   KC_R,   KC_T,   KC_Y,   KC_U,    KC_I,   KC_O,     KC_P, KC_NO, KC_7,KC_8,KC_9,
   LT(_NAV,KC_A),  KC_S,  KC_D,  KC_F,   KC_G,   KC_H,  KC_J,   KC_K,  KC_L, KC_QUOT, KC_NO,KC_4,KC_5,KC_6,
   MT(MOD_LSFT, KC_Z),   KC_X,   KC_C,   KC_V,   KC_B,   KC_N,   KC_M, KC_COMMA, KC_DOT,KC_SLSH, KC_NO,KC_1,KC_2,KC_3,
  KC_LCTL, KC_LALT, LT(_NUM_SYM,KC_SPACE), LT(_NUM_SYM,KC_SPACE), LT(_NUM_SYM,KC_SPACE), LT(_NUM_SYM,KC_SPACE), LT(_NUM_SYM,KC_SPACE), LT(_NUM_SYM,KC_SPACE), KC_LGUI, KC_NO, KC_NO,  KC_0, KC_DOT, KC_ENT
  ),

  [_NUM_SYM] = LAYOUT(
KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
KC_TRNS, DYN_REC_START1, DYN_MACRO_PLAY1, KC_TRNS, KC_TRNS, KC_SCLN, KC_MINS, KC_EQL, KC_QUOT, KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
KC_TRNS, DYN_REC_START2, DYN_MACRO_PLAY2, DYN_REC_STOP, KC_TRNS, KC_TRNS, KC_TRNS, KC_LBRC, KC_RBRC,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
KC_TRNS, KC_TRNS,      KC_TRNS,        KC_TRNS, KC_TRNS,KC_TRNS, KC_TRNS,      KC_TRNS,        KC_TRNS, KC_TRNS,KC_TRNS, KC_TRNS,      KC_TRNS,        KC_TRNS
),


  [_NAV] = LAYOUT(
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_UP, KC_END, KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
KC_TRNS, KC_TRNS, KC_BSPC, KC_DEL, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_RGHT, KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,KC_TRNS,
KC_TRNS, KC_TRNS,      KC_TRNS,        KC_TRNS, KC_TRNS,KC_TRNS, KC_TRNS,      KC_TRNS,        KC_TRNS, KC_TRNS,KC_TRNS, KC_TRNS,      RESET,        RESET
),


};


