VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += st7789_spi
POINTING_DEVICE_DRIVER = cirque_pinnacle_spi
POINTING_DEVICE_ENABLE = yes
VIALRGB_ENABLE = yes
