// Copyright 2022 xia0 (@xia0)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define VIAL_KEYBOARD_UID {0x35, 0xEB, 0x39, 0xAE, 0x97, 0x53, 0xAB, 0x92}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1, 2 }

#define VIAL_ENCODER_KEYCODE_DELAY 10
#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, KC_MEDIA_REWIND, KC_MEDIA_FAST_FORWARD, KC_MS_DOWN, KC_MS_UP, KC_MS_LEFT, KC_MS_RIGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }
