VIA_ENABLE = yes

VIAL_ENABLE = yes
LTO_ENABLE = yes # reduce firmware size
#VIALRGB_ENABLE = yes
#RGB_MATRIX_ENABLE= yes

#RGB_MATRIX_DRIVER = is31fl3746a

COMBO_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no

AVR_USE_MINIMAL_PRINTF = yes

MUSIC_ENABLE = no

