#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = {
    {KC_GESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7}, 
    {KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_CAPSLOCK}, 
    {KC_LSHIFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_CAPSLOCK}, 
    {KC_LCTRL, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_LALT, KC_LGUI}, 
    {KC_SPACE, KC_N, KC_M, KC_COMMA, KC_NO, KC_NO, KC_RALT, MO(1)}, 
    {KC_RIGHT, KC_DOWN, KC_LEFT, KC_DOT, KC_SLASH, KC_RSHIFT, KC_UP, KC_END}, 
    {KC_PGDOWN, KC_J, KC_K, KC_L, KC_SCOLON, KC_QUOTE, KC_ENTER, KC_NO}, 
    {KC_BSLASH, KC_U, KC_I, KC_O, KC_P, KC_LBRACKET, KC_RBRACKET, KC_PGUP}, 
    {KC_BSPACE, KC_HOME, KC_I, KC_8, KC_9, KC_0, KC_MINUS, KC_EQUAL},
    {KC_DELETE, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  [1] = {
    {KC_GRAVE, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7}, 
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_TOG, RGB_MOD, KC_TRNS, KC_TRNS}, 
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_HUI, RGB_SAI, RGB_VAI, KC_TRNS}, 
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_CALC, RGB_HUD, RGB_SAD, KC_TRNS, KC_TRNS}, 
    {KC_TRNS, RGB_VAD, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_TRNS}, 
    {KC_VOLU, KC_VOLD, KC_MUTE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}, 
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO}, 
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}, 
    {KC_DELETE, KC_TRNS, KC_TRNS, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
};

#include "led.h"
#include "rgblight.h"
extern LED_TYPE indicator_color[LOGIC_INDICATOR_NUM];
extern uint8_t indicator_state;
void rgb_extra_process(LED_TYPE *rgbled) {
    if (indicator_state) {
        rgbled[0] = indicator_color[0];
    }
}