#define VIAL_KEYBOARD_UID {0x5C, 0x62, 0x97, 0xFD, 0x6A, 0x4C, 0x59, 0x89}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0  }
#define VIAL_UNLOCK_COMBO_COLS { 0, 11 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4

// #define LAYER_STATE_8BIT
// #define VIAL_TAP_DANCE_ENTRIES 4
// #define VIAL_COMBO_ENTRIES 4
