VIA_ENABLE = yes
VIAL_ENABLE = yes
KEY_LOCK_ENABLE = no

# must reduce EEPROM usage
LTO_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

QMK_SETTINGS = no

CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
