#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 7

#define VIAL_ENCODER_DEFAULT {KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}

#define VIAL_ENCODER_KEYCODE_DELAY 10

#define VIAL_KEYBOARD_UID {0xB3, 0x30, 0xE4, 0x75, 0xF9, 0x3A, 0x9B, 0x18}

#define VIAL_UNLOCK_COMBO_ROWS {1, 4}
#define VIAL_UNLOCK_COMBO_COLS {0, 13}
