BOOTMAGIC_ENABLE = yes
NKRO_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
LTO_ENABLE = yes
CONSOLE_ENABLE = no        # Console for debug
COMMAND_ENABLE = no        # Commands for debug and configuration
