#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = {
    {KC_ESCAPE, KC_NO, KC_PSCREEN, KC_PAUSE, KC_SCROLLLOCK, KC_PGUP, KC_HOME, KC_INSERT},
    {KC_F12, KC_UP, KC_RIGHT, KC_DOWN, KC_LEFT, KC_DELETE, KC_END, KC_PGDOWN},
    {KC_F11, KC_BSPACE, KC_BSLASH, KC_ENTER, KC_BSPACE, KC_APPLICATION, KC_RCTRL, KC_BSPACE},
    {KC_F10, KC_RBRACKET, KC_RSHIFT, MO(1), KC_EQUAL, KC_QUOTE, KC_SLASH, KC_LBRACKET},
    {KC_F9, KC_MINUS, KC_RGUI, KC_RALT, KC_DOT, KC_SCOLON, KC_P, KC_0},
    {KC_F8, KC_COMMA, KC_L, KC_O, KC_9, KC_I, KC_K, KC_M},
    {KC_F7, KC_NO, KC_SPACE, KC_N, KC_J, KC_U, KC_8, KC_7},
    {KC_F6, KC_Y, KC_H, KC_B, KC_NO, KC_V, KC_G, KC_T},
    {KC_F5, KC_6, KC_C, KC_F, KC_R, KC_5, KC_D, KC_E},
    {KC_F4, KC_NO, KC_4, KC_X, KC_LALT, KC_S, KC_W, KC_NO},
    {KC_F3, KC_3, KC_Z, KC_LGUI, KC_LCTRL, KC_A, KC_Q, KC_2},
    {KC_F2, KC_1, KC_NONUS_BSLASH, KC_LSHIFT, KC_CAPSLOCK, KC_TAB, KC_GRAVE, KC_F1},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  }, 
  [1] = {
    {KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_VOLU, KC_VOLU, KC_VOLD, KC_MUTE, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_MOD, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_NO, KC_TRNS, RGB_VAD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, RGB_VAI, RGB_SAD, KC_NO, RGB_HUD, RGB_SAI, RGB_MOD},
    {KC_TRNS, KC_TRNS, KC_CALC, RGB_HUI, RGB_TOG, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  }, 
};

#include "led.h"
#include "rgblight.h"
extern uint8_t indicator_color_config[3];
void rgb_extra_process(LED_TYPE *rgbled) {
    if (indicator_color_config[2] & 1) {
        for (uint8_t i=2; i<6; i++) {
            rgbled[i] = rgbled[0];
        }
    }
}