VIA_ENABLE = yes
VIAL_ENABLE = yes
VIAL_INSECURE = yes
# QMK_SETTINGS = no
# KEY_OVERRIDE_ENABLE = no
# COMBO_ENABLE = no
VIALRGB_ENABLE = yes

CONSOLE_ENABLE = yes
# TRACKPOINT_AUTO_MOUSE_ENABLE = yes