VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes

SPACE_CADET_ENABLE = yes
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no

CAPS_WORD_ENABLE = yes
AUTOSHIFT_ENABLE = no
KEY_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
