VIA_ENABLE = yes
VIAL_ENABLE = yes

# Reduce firmware size:
LTO_ENABLE = yes
MAGIC_ENABLE = no
QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
