CONSOLE_ENABLE = no
POINTING_DEVICE_ENABLE = no
VIA_ENABLE          = yes
VIAL_ENABLE         = yes
RGBLIGHT_ENABLE     = no
RGB_MATRIX_ENABLE   = no # Can't have RGBLIGHT and RGB_MATRIX at the same time.
COMBO_ENABLE        = no
QMK_SETTINGS        = no
MOUSEKEY_ENABLE     = no
EXTRAKEY_ENABLE     = no
CONSOLE_ENABLE      = no
