LTO_ENABLE = yes
COMMAND_ENABLE = no
ifdef RGB_MATRIX_ENABLE
	VIALRGB_ENABLE = yes
	TAP_DANCE_ENABLE = yes
	ENCODER_ENABLE = yes
	VIAL_ENCODERS_ENABLE = yes
	VIA_ENABLE = yes
	VIAL_ENABLE = yes
endif

