VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes
QMK_SETTINGS = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

AVR_USE_MINIMAL_PRINTF = yes
EXTRAKEY_ENABLE = yes

# Reduce the firmware size:
BACKLIGHT_ENABLE = no
BOOTMAGIC_ENABLE = no
COMBO_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no
KEY_OVERRIDE_ENABLE = no
LEADER_ENABLE = no
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
RGB_MATRIX_ENABLE = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = no
VIALRGB_ENABLE = no
