#pragma once

#define VIAL_KEYBOARD_UID {0xC2, 0x3A, 0x2B, 0xF5, 0xE0, 0xD3, 0x55, 0xE7}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define VIAL_MACRO_ENTRIES 16
#define DYNAMIC_KEYMAP_MACRO_COUNT 16
#define VIAL_COMBO_ENTRIES 16
#define VIAL_TAP_DANCE_ENTRIES 8
