#pragma once

#define VIAL_KEYBOARD_UID {0xC2, 0x3A, 0x2B, 0xF5, 0xE0, 0xD3, 0x55, 0xE7}
#define VIAL_UNLOCK_COMBO_ROWS {0, 0}
#define VIAL_UNLOCK_COMBO_COLS {0, 1}

#define DYNAMIC_KEYMAP_LAYER_COUNT 6
#define VIAL_MACRO_ENTRIES 64
#define DYNAMIC_KEYMAP_MACRO_COUNT 64
#define VIAL_COMBO_ENTRIES 32
#define VIAL_TAP_DANCE_ENTRIES 32
#define DYNAMIC_KEYMAP_KEY_OVERRIDE_COUNT 0
