VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = yes
LTO_ENABLE = yes
ENCODER_MAP_ENABLE = yes
KEY_OVERRIDE_ENABLE = no

MOUSEKEY_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

REPEAT_KEY_ENABLE = no
