/* SPDX-Licanse-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x2F, 0xE9, 0x9C, 0x35, 0xA0, 0x07, 0xEA, 0x2B}
#define VIAL_UNLOCK_COMBO_ROWS { 0,3 }
#define VIAL_UNLOCK_COMBO_COLS { 6,2 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 3
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define NO_ACTION_ONESHOT
#define LAYER_STATE_8BIT


