VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = no

MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
COMBO_ENABLE = no
NKRO_ENABLE = no
RING_BUFFERED_6KRO_REPORT_ENABLE = no
AUDIO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

LEADER_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
BUETOOTH_ENABLE = no
RAW_ENABLE = no
VIRTSER_ENABLE = no

TAP_DANCE_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
BACKLIGHT_ENABLE = no
