VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no

ifeq ($(strip $(CONVERT_TO)), )
    QMK_SETTINGS = no
endif

COMBO_ENABLE = no
