#define VIAL_KEYBOARD_UID {0x2A, 0xF8, 0xE3, 0xFB, 0x33, 0xBF, 0x8F, 0xBA}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 0  }
#define VIAL_UNLOCK_COMBO_COLS { 0, 9 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define LAYER_STATE_8BIT
// #define VIAL_COMBO_ENTRIES 8
// #define VIAL_TAP_DANCE_ENTRIES 8
