MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
BACKLIGHT_ENABLE = no
BLUETOOTH_ENABLE = no
COMMAND_ENABLE = no
UNICODE_ENABLE = no
EXTRAKEY_ENABLE = no
AUDIO_ENABLE = no
LEADER_ENABLE = no
MIDI_ENABLE = no
BLUETOOTH_ENABLE = no
SPLIT_KEYBOARD = no
AUTO_SHIFT_ENABLE = no
VIALRGB_ENABLE = no
DYNAMIC_MACRO_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes
LT0_ENABLE = yes
TAP_DANCE_ENABLE = yes
NKRO_ENABLE = yes           # Enable N-Key Rollover
QMK_SETTINGS = yes
DEBOUNCE_TYPE = sym_defer_pr

EXTRAFLAGS += -flto