VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes
QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = yes

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
