#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  {
    {KC_GESC, LT(2, KC_TAB), KC_Q, KC_A, KC_W, KC_S, KC_E, KC_D},
    {KC_NO, KC_X, KC_C, KC_LALT, KC_LCTRL, KC_NO, KC_Z, KC_LSHIFT},
    {KC_F, KC_R, KC_T, KC_G, KC_Y, KC_U, KC_H, KC_J},
    {KC_M, KC_SPACE, KC_N, KC_B, KC_B, KC_X, LT(1, KC_SPACE), KC_V},
    {KC_K, KC_I, KC_O, KC_L, KC_P, KC_SCOLON, LGUI_T(KC_BSLASH), KC_BSPACE},
    {KC_ENTER, LT(3, KC_RIGHT), RSFT_T(KC_UP), KC_NO, KC_DOWN, KC_LEFT, KC_COMMA, KC_DOT},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  {
    {KC_GRAVE, KC_TRNS, KC_1, KC_TRNS, KC_2, KC_TRNS, KC_3, KC_BTN1},
    {KC_NO, KC_TRNS, KC_MS_L, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS},
    {KC_MS_U, KC_4, KC_5, KC_BTN2, KC_6, KC_7, KC_LBRACKET, KC_RBRACKET},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_MS_R, KC_MS_R, KC_TRNS, KC_TRNS, KC_MS_D},
    {KC_TRNS, KC_8, KC_9, KC_TRNS, KC_0, KC_QUOTE, KC_MINUS, KC_EQUAL},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_SLASH},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  {
    {KC_CAPSLOCK, KC_TRNS, KC_PSCREEN, KC_DELETE, KC_PGUP, KC_PGDOWN, KC_HOME, KC_END},
    {KC_NO, KC_SCROLLLOCK, KC_F4, KC_TRNS, KC_TRNS, KC_NO, KC_PAUSE, KC_TRNS},
    {KC_F5, KC_F2, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LGUI(KC_V)},
    {KC_TRNS, KC_INSERT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_RCTRL, KC_RALT, KC_TRNS, KC_RGUI},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  {
    {KC_TRNS, KC_TRNS, KC_F1, KC_TRNS, KC_F2, KC_TRNS, KC_F3, KC_TRNS},
    {KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_F4, KC_F5, KC_TRNS, KC_F6, KC_F7, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_F8, KC_F9, KC_TRNS, KC_F10, KC_TRNS, KC_F11, KC_F12},
    {KC_MPLY, KC_TRNS, KC_VOLU, KC_NO, KC_VOLD, KC_MUTE, KC_MPRV, KC_MNXT},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },

};

