VIA_ENABLE = yes
VIAL_ENABLE = yes

OLED_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

MOUSEKEY_ENABLE		= no
QMK_SETTINGS		= no
TAP_DANCE_ENABLE	= no
COMBO_ENABLE		= no
KEY_OVERRIDE_ENABLE	= no

RGB_MATRIX_ENABLE = no
VIALRGB_ENABLE = no
#CONVERT_TO = rp2040_ce
