VIA_ENABLE = yes
LTO_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = yes
QMK_SETTINGS = no
COMBOS_ENABLE = yes
TAP_DANCE_ENABLE = no

KEY_OVERRIDE_ENABLE = no
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
MAGIC_ENABLE = no
