#pragma once

#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64

// Split
#define SERIAL_USART_FULL_DUPLEX
#define SELECT_SOFT_SERIAL_SPEED 2
#define MASTER_LEFT
#define SERIAL_DEBUG
#define SPLIT_LAYER_STATE_ENABLE

// Serial pins differ per side
#ifdef RIGHT_SIDE
#    define SERIAL_USART_TX_PIN GP16
#    define SERIAL_USART_RX_PIN GP17
#else
#    define SERIAL_USART_TX_PIN GP0
#    define SERIAL_USART_RX_PIN GP1
#endif

// WS2812
#define WS2812_DI_PIN GP24

// OLED
#define OLED_DISPLAY_128X32
#define OLED_TIMEOUT 0
#define OLED_FONT_H "keyboards/hidpress/ambi_test/glcdfont.c"
#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP12
#define I2C1_SCL_PIN GP13

// Joystick / Pointing device
#define ANALOG_JOYSTICK_AUTO_AXIS
#define ANALOG_JOYSTICK_SPEED_REGULATOR 20
#define ANALOG_JOYSTICK_CUTOFF
#define ANALOG_JOYSTICK_X_AXIS_PIN GP29
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP28
#define ANALOG_JOYSTICK_ENABLE
#define POINTING_DEVICE_LEFT
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_INVERT_X

// Encoder (right side only)
#define ENCODER_RESOLUTION 4
#define ENCODERS_PAD_A_RIGHT { GP28 }
#define ENCODERS_PAD_B_RIGHT { GP29 }

// Matrix
#define MATRIX_ROWS 8
#define MATRIX_COLS 8
#define MATRIX_ROW_PINS_RIGHT { GP0, GP11, GP25, GP26 }
#define MATRIX_COL_PINS_RIGHT { GP1, GP2, GP3, GP4, GP5, GP10, GP27, NO_PIN }
