VIA_ENABLE = yes
VIAL_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
COMBO_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

COMMAND_ENABLE = no
CONSOLE_ENABLE = no

LTO_ENABLE = yes

KEY_OVERRIDE_ENABLE = no

TAP_DANCE_ENABLE = no
QMK_SETTINGS = no
