VIA_ENABLE = yes
VIAL_ENABLE = yes
MCU = RP2040
BOOTLOADER = rp2040

ENCODER_MAP_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
COMBOS_ENABLE = yes
TAP_DANCE_ENABLE = yes

OLED_ENABLE = yes
OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE = yes

MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
AUDIO_ENABLE = no
