/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x32, 0x1C, 0xDD, 0xBB, 0x80, 0x8F, 0xC1, 0x7F}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 2 }

// Disable some animations to decrease firmware size:
//
//#undef RGBLIGHT_ANIMATIONS
//#undef RGBLIGHT_EFFECT_BREATHING
//#undef RGBLIGHT_EFFECT_RAINBOW_MOOD
//#undef RGBLIGHT_EFFECT_RAINBOW_SWIRL
//#undef RGBLIGHT_EFFECT_SNAKE
//#undef RGBLIGHT_EFFECT_KNIGHT
//#undef RGBLIGHT_EFFECT_CHRISTMAS
//#undef RGBLIGHT_EFFECT_STATIC_GRADIENT
//#undef RGBLIGHT_EFFECT_RGB_TEST
//#undef RGBLIGHT_EFFECT_ALTERNATING
//#undef RGBLIGHT_EFFECT_TWINKLE
//
//#undef ENABLE_RGB_MATRIX_ALPHAS_MODS
//#undef ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN
//#undef ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT
//#undef ENABLE_RGB_MATRIX_BREATHING
//#undef ENABLE_RGB_MATRIX_BAND_SAT
//#undef ENABLE_RGB_MATRIX_BAND_VAL
//#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT
//#undef ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL
//#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT
//#undef ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL
//#undef ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
//#undef ENABLE_RGB_MATRIX_CYCLE_UP_DOWN
//#undef ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON
//#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN
//#undef ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL
//#undef ENABLE_RGB_MATRIX_CYCLE_PINWHEEL
//#undef ENABLE_RGB_MATRIX_CYCLE_SPIRAL
//#undef ENABLE_RGB_MATRIX_DUAL_BEACON
//#undef ENABLE_RGB_MATRIX_RAINBOW_BEACON
//#undef ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS
//#undef ENABLE_RGB_MATRIX_RAINDROPS
//#undef ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
//#undef ENABLE_RGB_MATRIX_HUE_BREATHING
//#undef ENABLE_RGB_MATRIX_HUE_PENDULUM
//#undef ENABLE_RGB_MATRIX_HUE_WAVE
//#undef ENABLE_RGB_MATRIX_PIXEL_FRACTAL
//#undef ENABLE_RGB_MATRIX_PIXEL_RAIN
//
//#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE
//#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE
//#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
//#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
//#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS
//#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS
//#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS
//#undef ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS
//#undef ENABLE_RGB_MATRIX_SPLASH
//#undef ENABLE_RGB_MATRIX_MULTISPLASH
//#undef ENABLE_RGB_MATRIX_SOLID_SPLASH
//#undef ENABLE_RGB_MATRIX_SOLID_MULTISPLASH
