AUDIO_DRIVER = pwm_hardware
AUDIO_ENABLE = yes
COMBO_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
RGBLIGHT_ENABLE = yes
LTO_ENABLE = yes
OLED_ENABLE = yes
QMK_SETTINGS = no
RGBLIGHT_ENABLE = no
MOUSEKEY_ENABLE = yes
SERIAL_DRIVER = vendor
SPLIT_KEYBOARD = yes
SWAP_HANDS_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes



