VIA_ENABLE = yes
VIAL_ENABLE = yes

LTO_ENABLE = yes
QMK_SETTINGS_ENABLE = yes
CAPS_WORD_ENABLE = yes

MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = yes
MAGIC_ENABLE = no
MUSIC_ENABLE = no
NKRO_ENABLE = no
BOOTMAGIC_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
ENCODER_ENABLE = no
OLED_ENABLE = no
VIAL_COMBO_ENABLE = yes
VIAL_KEY_OVERRIDE_ENABLE = yes
VIAL_INSECURE = yes
REPEAT_KEY_ENABLE = no
TRI_LAYER_ENABLE = no
