/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x82, 0x1C, 0x92, 0xC7, 0x6B, 0xC1, 0xB2, 0xA9}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 2 }
#define VIAL_UNLOCK_COMBO_COLS { 1, 13 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 4

#define VIAL_ENCODER_DEFAULT { KC_VOLD, KC_VOLU, KC_VOLD, KC_VOLU, KC_MS_WH_DOWN, KC_MS_WH_UP, KC_MS_WH_DOWN, KC_MS_WH_UP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }

#define VIAL_TAP_DANCE_ENTRIES 5
#define VIAL_COMBO_ENTRIES 5
#define VIAL_KEY_OVERRIDE_ENTRIES 5

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
