#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  {
    {KC_ESCAPE, KC_TAB, KC_Q, KC_W, KC_1, KC_2, KC_3, KC_E},
    {KC_Z, KC_LGUI, KC_S, KC_LCTRL, KC_R, KC_LSHIFT, KC_A, KC_CAPSLOCK},
    {KC_4, KC_R, KC_5, KC_T, KC_6, KC_7, KC_Y, KC_U},
    {KC_B, KC_G, KC_V, KC_C, KC_LALT, KC_X, KC_F, KC_D},
    {KC_8, KC_I, KC_9, KC_0, KC_MINUS, KC_O, KC_P, KC_LBRACKET},
    {KC_L, KC_COMMA, KC_M, KC_SPACE, KC_N, KC_K, KC_J, KC_H},
    {KC_EQUAL, KC_BSPACE, KC_K, KC_HOME, KC_RBRACKET, KC_BSLASH, KC_NO, KC_NO},
    {KC_ENTER, KC_LEFT, MO(1), KC_RALT, KC_QUOTE, KC_SLASH, KC_DOT, KC_SCOLON},
    {KC_PGUP, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_PGDOWN, KC_END, KC_RIGHT, KC_DOWN, KC_UP, KC_RSHIFT},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  {
    {KC_GRAVE, KC_TRNS, KC_TRNS, KC_TRNS, KC_1, KC_2, KC_3, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_4, KC_TRNS, KC_5, KC_TRNS, KC_6, KC_7, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_CALC, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_8, KC_TRNS, KC_9, KC_0, KC_MINUS, KC_TRNS, KC_PSCREEN, KC_SCROLLLOCK},
    {KC_INSERT, KC_VOLU, KC_MUTE, KC_TRNS, KC_VOLD, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_EQUAL, KC_DELETE, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO},
    {KC_TRNS, KC_MUTE, KC_TRNS, KC_TRNS, KC_PGUP, KC_PGDOWN, KC_END, KC_HOME},
    {KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_VOLU, KC_VOLD, KC_VOLU, KC_TRNS},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
};
