BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes

# reviung34_rgb
RGBLIGHT_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = no
COMBO_ENABLE = no

CAPS_WORD_ENABLE = no
LAYER_LOCK_ENABLE = no
REPEAT_KEY_ENABLE = no
