// Copyright 2026 Sarah Helmbrecht (@skhelmbrecht)
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#define MATRIX_ROWS 14
#define MATRIX_COLS 8

#define DEBOUNCE 0

#define WS2812_DI_PIN B15
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_GRB

#define RGB_MATRIX_LED_COUNT 1
#define DRIVER_LED_TOTAL RGB_MATRIX_LED_COUNT
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_DEFAULT_HUE 0
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 255
#define RGB_MATRIX_DEFAULT_FLAGS LED_FLAG_INDICATOR
