#pragma once
#define VIAL_KEYBOARD_UID {0x3C, 0xB6, 0x24, 0x57, 0x7C, 0xDA, 0xEC, 0x4C}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 6 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 7 }
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_TAP_DANCE_ENTRIES 1
#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION
#define NO_ACTION_ONESHOT
