LTO_ENABLE = yes
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor
# EEPROM_DRIVER = wear_leveling
# WEAR_LEVELING_DRIVER = rp2040_flash
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
AUDIO_ENABLE = no           # Audio output
WS2812_DRIVER = vendor
RGBLIGHT_SUPPORTED = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_SUPPORTED = yes
RGB_MATRIX_DRIVER = WS2812
OLED_ENABLE     = yes
OLED_DRIVER     = SSD1306
