VIAL_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes
QMK_SETTINGS = yes

RGB_MATRIX_ENABLE = no
RGBLIGHT_ENABLE = no
OLED_ENABLE = no
BOOTMAGIC_ENABLE = no
COMMAND_ENABLE = no
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
