#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [0] = {
    {KC_F1, KC_F2, KC_GESC, KC_TAB, KC_1, KC_Q, KC_2, KC_W},
    {KC_LGUI, KC_LGUI, KC_LCTRL, KC_LSHIFT, KC_F5, KC_F4, KC_F3, KC_CAPSLOCK},
    {KC_3, KC_E, KC_4, KC_R, KC_5, KC_6, KC_T, KC_NO},
    {KC_C, KC_F, KC_LALT, KC_X, KC_D, KC_Z, KC_S, KC_A},
    {KC_H, KC_Y, KC_7, KC_J, KC_U, KC_8, KC_I, KC_K},
    {KC_SPACE, KC_M, KC_B, KC_N, KC_B, KC_SPACE, KC_V, KC_G},
    {KC_9, KC_O, KC_L, KC_0, KC_MINUS, KC_EQUAL, KC_P, KC_SCOLON},
    {KC_SLASH, KC_RALT, KC_NO, KC_NO, KC_NO, KC_DOT, LT(1,KC_APPLICATION), KC_COMMA},
    {KC_LBRACKET, KC_QUOTE, KC_RBRACKET, KC_BSPACE, KC_NO, KC_BSLASH, KC_ENTER, KC_NO},
    {KC_RSHIFT, LT(1,KC_DELETE), KC_RCTRL, KC_RGUI, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
  [1] = {
    {KC_TRNS, KC_TRNS, KC_GRAVE, KC_TRNS, KC_F1, KC_TRNS, KC_F2, KC_UP},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_F3, KC_TRNS, KC_F4, KC_TRNS, KC_F5, KC_F6, KC_TRNS, KC_NO},
    {KC_CALC, KC_TRNS, KC_TRNS, KC_TRNS, KC_RIGHT, KC_TRNS, KC_DOWN, KC_LEFT},
    {KC_TRNS, KC_TRNS, KC_F7, KC_TRNS, KC_TRNS, KC_F8, KC_TRNS, KC_TRNS},
    {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
    {KC_F9, KC_TRNS, KC_INSERT, KC_F10, KC_F11, KC_F12, KC_PSCREEN, KC_HOME},
    {KC_PGDOWN, KC_MUTE, KC_NO, KC_NO, KC_NO, KC_END, KC_TRNS, KC_DELETE},
    {KC_SCROLLLOCK, KC_PGUP, KC_PAUSE, KC_DELETE, KC_NO, KC_TRNS, KC_TRNS, KC_NO},
    {KC_VOLU, KC_TRNS, KC_VOLU, KC_VOLD, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO},
    {KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO}
  },
};
