/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x25, 0x2C, 0x3E, 0x99, 0x55, 0x61, 0xC3, 0x58}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 3 }

#define VIAL_COMBO_ENTRIES 69
#define DYNAMIC_KEYMAP_LAYER_COUNT 32
#define TAPPING_TERM 200

#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define RGB_MATRIX_LED_COUNT 36