VIA_ENABLE = yes
VIAL_ENABLE = yes
LT0_ENABLE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

VIAL_ENCODERS_ENABLE = yes

VIAL_INSECURE = yes
