VIA_ENABLE = yes
VIAL_ENABLE = yes

VIALRGB_ENABLE = yes
ENCODER_MAP_ENABLE = yes
BOOTMAGIC_ENABLE = yes
MAGIC_ENABLE = yes
OS_DETECTION_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
CAPS_WORD_ENABLE = yes
