/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x69, 0x99, 0x17, 0xE3, 0x75, 0xA5, 0x3B, 0x1F}
#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#define VIAL_UNLOCK_COMBO_ROWS {0,6}
#define VIAL_UNLOCK_COMBO_COLS {0,6}

#undef RGBLIGHT_EFFECT_CHRISTMAS
#undef RGBLIGHT_EFFECT_RGB_TEST
