#pragma once

#define VIAL_KEYBOARD_UID {0xBE, 0xA2, 0x9B, 0x4C, 0x6E, 0x78, 0xDA, 0x7D}

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define VIAL_TAP_DANCE_ENTRIES 12

#define VIAL_COMBO_ENTRIES 48

#define DYNAMIC_KEYMAP_MACRO_COUNT 16

#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 5 }