MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

AUTO_SHIFT_ENABLE = yes
COMBO_ENABLE = yes
MIDI_ENABLE = no
AUDIO_ENABLE = no
BLUETOOTH_ENABLE = no
LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

VIA_ENABLE = yes
VIAL_ENABLE = yes

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = no

OLED_DRIVER_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
