#pragma once

#define WS2812_DI_PIN A13

#ifdef WS2812_DI_PIN
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD   
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_CHRISTMAS      
#define RGBLIGHT_EFFECT_STATIC_GRADIENT  
#define RGBLIGHT_EFFECT_KNIGHT       
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE


#define RGBLIGHT_SLEEP
#define RGBLIGHT_LED_COUNT 5
#define RGBLIGHT_DEFAULT_VAL 128
#define RGBLIGHT_LIMIT_VAL 128
/* #define RGBLIGHT_HUE_STEP 8 */
/* #define RGBLIGHT_SAT_STEP 8 */
/* #define RGBLIGHT_VAL_STEP 8 */
#endif

