#pragma once

#define VIAL_KEYBOARD_UID {0xB3, 0x12, 0x72, 0xC5, 0x93, 0x2E, 0x5F, 0x82}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 12 }

#undef RGBLIGHT_ALTERNATING
#undef RGBLIGHT_EFFECT_CHRISTMAS

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
